import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/common/Header";
import Footer from "@/components/common/Footer";
import StoreProvider from "@/lib/redux/StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Movie Night",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <header className="bg-darkBlue text-white font-medium p-4 w-full">
          <Header />
        </header>
        <StoreProvider>{children}</StoreProvider>
        <footer className="bg-darkBlue text-white py-6">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
